name:                bmbnd
version:             0.0.1.0
author:              "Jason Balaci"
maintainer:          "Drasil Research Team"
synopsis:	           "Beam bending analysis program case study"
github:              JacquesCarette/Drasil
homepage:            https://jacquescarette.github.io/Drasil/
description:         Please see the README on GitHub at <https://github.com/JacquesCarette/Drasil#readme>

extra-source-files: []

dependencies:
- base >= 4.7 && < 5
- lens
- directory
- drasil-code
- drasil-code-base
- drasil-data
- drasil-database
- drasil-docLang
- drasil-gen
- drasil-gool
- drasil-lang
- drasil-metadata
- drasil-printers
- drasil-theory
- drasil-utils

library:
  source-dirs: lib
  when:
  - condition: false
    other-modules: Paths_bmbnd

executables:
  bmbnd:
    main: Main
    source-dirs: app 
    ghc-options:
    - -Wall
    - -Wredundant-constraints
    - -threaded
    - -O2
    dependencies:
    - bmbnd
    when:
    - condition: false
      other-modules: Paths_bmbnd
