on:
  push:
  pull_request:
    branches: master
  workflow_dispatch:
name: Build
defaults:
  run:
    shell: bash
    working-directory: code
env:
  is_deployment: ${{ github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}
jobs:
  auto-cancel:
    if: | 
      github.event_name == 'pull_request'
      || github.event_name == 'workflow_dispatch'
      || (github.event_name == 'push' && (github.ref == 'refs/heads/master' || contains(github.event.head_commit.message, '[workflow-trigger]')))
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
  build:
    needs: auto-cancel
    name: "Build & Deploy"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
